Another attempt to verify static executables
ldd does not return exit code of 1 any more for static, and "file" reports dynamic on arm64 even when it is not.  So now we look at the output of ldd instead.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -119,7 +119,6 @@ jobs:
           sudo apt update
           sudo apt install -y \
               cmake \
-              file \
               ninja-build
 
       - name: Install Mac deps
@@ -206,14 +205,16 @@ jobs:
           # Check static executables
           if [[ "${{ runner.os }}" == "Linux" ]]; then
             echo "::group::Check static executables"
-            # Capture file information about the executables, but also let it
-            # be logged to stdout.
-            file -L build/packager/{packager,mpd_generator} | tee static.log
-            # The phrase "dynamically linked" means we messed this up.  Fail if
-            # we find it.
-            if cat static.log | grep -q dynamically; then
-              exit 1
-            fi
+            for exe in build/packager/{packager,mpd_generator}; do
+              # Capture information about the executables, but also let it be
+              # logged to stdout.
+              ldd "$exe" | tee static.log
+              # The phrase "statically linked" means we got it right.  Fail if
+              # we don't find it.
+              if ! cat static.log | grep -q statically; then
+                exit 1
+              fi
+            done
             echo "::endgroup::"
           fi
 
